spring:
  application:
    name: catalog-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
#  jpa:
#    hibernate:
#      ddl-auto: none  # Important: Let Maven Flyway handle all schema changes
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Flyway completely disabled in Spring Boot - managed by Maven only
#  flyway:
#    enabled: true
#    locations: classpath:db/migration

server:
  port: 8081
  shutdown: graceful

catalog:
  page-size: 10

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full




