spring:
  application:
    name: catalog-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  flyway:
    clean-disabled: true
    baseline-on-migrate: true
    locations: classpath:db.migration
    schemas: public



#  jpa:
#    hibernate:
#      ddl-auto: none  # Important: Let Maven Flyway handle all schema changes
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Flyway completely disabled in Spring Boot - managed by Maven only
#  flyway:
#  #  enabled: true
#  #  locations: filesystem:db/migration
#    baselineOnMigrate: true
#    baseline-on-migrate: true
#
#flyway:
##    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
##    user: ${DB_USERNAME:postgres}
##    password: ${DB_PASSWORD:postgres}
#    locations: filesystem:db/migration
#    baselineOnMigrate: true
#    baseline-on-migrate: true


server:
  port: 8081
  shutdown: graceful

logging:
  level:
    root: INFO
    org:
      flywaydb: DEBUG
catalog:
  page-size: 10

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full




