spring:
  application:
    name: order-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: sulaynd@gmail.com
    password: ioug koma jath insr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ######## Database Configuration  #########
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:25432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    open-in-view: false
    show-sql: true
  ######## RabbitMQ Configuration  #########
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

######## Order Service Configuration  #########
orders:
  catalog-service-url: http://localhost:8081
  order-events-exchange: orders-exchange
  new-orders-queue: new-orders
  delivered-orders-queue: delivered-orders
  cancelled-orders-queue: cancelled-orders
  error-orders-queue: error-orders
  publish-order-events-job-cron: '*/5 * * * * *'
  new-orders-job-cron: '*/10 * * * * *'


server:
  port: 8082
  shutdown: graceful

######## Catalog Service Configuration  #########
#order:
#  page-size: 10

######## Actuator Configuration  #########
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: '*'


######### Actuator Configuration  #########
#management.metrics.tags.application=${spring.application.name}
#management.tracing.enabled=false
#management.tracing.sampling.probability=1.0
#
########## Swagger Configuration  #########
#swagger.api-gateway-url=http://localhost:8989/orders
#
######## OAuth2 Configuration  #########
#OAUTH2_SERVER_URL=http://localhost:9191
#REALM_URL=${OAUTH2_SERVER_URL}/realms/bookstore
#spring.security.oauth2.resourceserver.jwt.issuer-uri=${REALM_URL}

###### Resilience4j for Circuit Breaker and Retry  #########
### Retry Configuration
resilience4j:
  retry:
    backends:
      catalog-service:
        max-attempts: 2
        wait-duration: 1s
#### Circuitbreaker Configuration
  circuitbreaker:
    backends:
      catalog-service:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 6
        minimum-number-of-calls: 4
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50