server:
  port: 8080
  shutdown: graceful

######## OAuth2 Security Configuration  #########
OAUTH2_SERVER_URL: http://localhost:9191
REALM_URL: ${OAUTH2_SERVER_URL}/realms/bookstore

spring:
  application:
    name: bookstore-webapp
  mvc:
    problemdetails:
      enabled: true


  security:
    oauth2:
      client:
        registration:
          bookstore-webapp:
            client-id: bookstore-webapp
            client-secret: TNFUjQKRplFJonzq9hA1SPYavVX4Syfp
            authorization-grant-type: authorization_code
            scope: openid, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/bookstore-webapp"
        provider:
          bookstore-webapp:
            issuer-uri: ${REALM_URL}



#  security:
#    oauth2:
#      client:
#        registration:
#          bookstore-webapp:
#            client-id: bookstore-webapp
#            client-secret: TNFUjQKRplFJonzq9hA1SPYavVX4Syfp
#            authorization-grant-type: authorization_code
#            scope: openid, profile
#            redirect-uri: {baseUrl}/login/oauth2/code/bookstore-webapp
#            #issuer-uri: ${REALM_URL}
#        provider:
#          bookstore-webapp:
#            issuer-uri: ${REALM_URL}
#            authorization-uri: ${REALM_URL}/protocol/openid-connect/auth
#            token-uri: ${REALM_URL}/protocol/openid-connect/token
#            jwk-set-uri: ${REALM_URL}/protocol/openid-connect/certs
#            user-info-uri: ${REALM_URL}/protocol/openid-connect/userinfo



#  security:
#    oauth2:
#      client:
#        registration:
#          bookstore-webapp:
#            client-id: bookstore-webapp
#            client-secret: P1sibsIrELBhmvK18BOzw1bUl96DcP2z
#            authorization-grant-type: authorization_code
#            scope: openid, profile
#            redirect-uri: {baseUrl}/login/oauth2/code/bookstore-webapp
#            issuer-uri: ${REALM_URL}

  ######## BookStore Application Configuration  #########
bookstore:
  api-gateway-url: http://localhost:8989

  ######## Actuator Configuration  #########
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0
