name: Catalog Service

on:
  push:
    paths:
      - catalog-service/** #then only change in catalog-service folder will get trigger
    branches:
      - '**' #trigger for any branch
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-service # specifying the working directory
     # DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-catalog-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v5 # checkout the code

      - name: Setup Java 21
        uses: actions/setup-java@v5 # setting java version
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
#
#      - name: Make Maven wrapper executable
#        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify  # running the verify build(execute both unit and integration tests)

#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and Publish Docker Image
#        run: |
#          ./mvnw spring-boot:build-image -DskipTests
#          echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
#          docker push $DOCKER_IMAGE_NAME
